version: "3"

networks:

  elk:
    external: false

services:

  elasticsearch:
    image: elasticsearch:2.4
    networks:
      - elk
    ports:
      - 9200:9200

  logstash:
    image: localhost:5000/logstash:1.0
    networks:
      - elk
    environment:
      - LOGSPOUT=ignore

  kibana:
    image: kibana:4.6
    networks: 
      - elk
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  logspout:
    image: gliderlabs/logspout
    networks:
      - elk
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://logstash:51415
    deploy:
      mode: global
