version: "3"

networks:

  proxy:
    external: true

services:

  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt
    networks:
      - proxy
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - DOMAIN_1=$DOMAINS
      - DOMAIN_COUNT=1
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=80
      replicas: 1
      placement:
        constraints: [node.id == $SSL_NODE_ID]