FROM centos:7

ENV HOME /var/jenkins_home \
    JENKINS_HOME /var/jenkins_home

RUN yum clean all && \
    yum install -y --setopt=tsflags=nodocs java-1.8.0-openjdk cpio rpm2cpio vim-tiny sshpass curl && \
    curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | tee /etc/yum.repos.d/jenkins.repo && \
    rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key && \
    yum install -y jenkins  && \
  # install docker
    curl -fsSL get.docker.com -o get-docker.sh && bash get-docker.sh && \ 
  # install kubectl
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl; mv ./kubectl /usr/local/bin/kubectl && \
    yum clean all ; rm -rf /var/cache/yum

RUN usermod -m -d $JENKINS_HOME jenkins && \
    chown -R jenkins $JENKINS_HOME && \
    usermod -aG docker jenkins

COPY jenkins.sh /usr/local/bin/jenkins.sh

# for main web interface:
EXPOSE 8080 50000

USER jenkins
ENV SECRETS_DIR=/run/secrets
# Whether to skip setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
# Creates username and password specified through environment variables JENKINS_USER_SECRET and JENKINS_PASS_SECRET
COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
 #    executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

# Install groovy global libraries for pipeline plugin
#COPY var/jenkins_home/org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml /usr/share/jenkins/ref/org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml

# Install a list of plugins from the file 'plugins.txt' and their dependencies
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

ENTRYPOINT ["/usr/local/bin/jenkins.sh"]