version: '3'

services:

  main:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

networks:
  proxy:
    external: true