version: '3'

services:

  main:
    image: dockersamples/visualizer
    ports:
      - ${HTTP_PORT:-8080}:8080
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
